#!/bin/bash                                                                                          

kill `lsof -t -i:5000`

kill `lsof -t -i:5001`

kill `lsof -t -i:5002`

kill `lsof -t -i:5003`

kill `lsof -t -i:5004`

kill `lsof -t -i:3000`
