#!/bin/bash

cd ./user_api
./launch&
cd ..
sleep 10

cd ./post_api
./launch&
cd ..

cd ./img_fetch_api
./launch&
cd ..

cd ./ml_api
./launch&
cd ..

cd ./stats_api
./launch&
cd ..


cd ./web_app
./launch&
cd ..
