swagger: "2.0"
info:
  description: "Api calls"
  version: "1.0.0"
  title: "DB APi routes"
#host: "none"
paths:
  /user/:
    post:
      tags:
      - "user"
      summary: "Create a user"
      description: ""
      operationId: "CreateUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
    get:
      tags:
      - "user"
      summary: "Get all users"
      description: ""
      operationId: "get_users"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
  /user/{user_id}:
    get:
      tags:
      - "user"
      summary: "Get user by id"
      description: ""
      operationId: "get_user_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
    put:
      tags:
      - "user"
      summary: "Update user"
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: false
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "success"
        404:
          description: "User not found"
    delete:
      tags:
      - "user"
      summary: "Delete user"
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        type: "integer"
      responses:
        404:
          description: "User not found"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"